openapi: "3.0.3"
info:
  title: ShoppingKuy
  version: "1.0"
servers:
  - url: http://localhost/3000/api/v1
    description: local
  - url: https://shopping-kuy/api/v1
    description: Deploy
paths:
  /admin/users:
    get:
      tags:
        - Dashboard
      description: Get all users
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: number
                        username:
                          type: string
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email:
                          type: string
                        role:
                          type: string
                          enum:
                            - CUSTOMER
                            - SELLER
              example:
                success: true
                message: Sukses ambil data user
                data:
                  - user_id: 1
                    username: johndoe345
                    first_name: John
                    last_name: Doe
                    email: johndoe345@gmail.com
                    role: CUSTOMER
                  - user_id: 2
                    username: zakymars456
                    first_name: Zaky
                    last_name: Mars
                    email: zakymars456@gmail.com
                    role: SELLER
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Data user tidak ditemukan.
  /admin/users/{id}:
    get:
      tags:
        - Dashboard
      description: Get user by Id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: number
                        username:
                          type: string
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email:
                          type: string
                        role:
                          type: string
                          enum:
                            - CUSTOMER
                            - SELLER
              example:
                success: true
                message: Sukses ambil data user
                data:
                  - user_id: 1
                    username: johndoe345
                    first_name: John
                    last_name: Doe
                    email: johndoe345@gmail.com
                    role: CUSTOMER
        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Data user tidak ditemukan.

  /auth/register:
    post:
      tags:
        - Authentication
      description: Create new user and send OTP code.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - first_name
                - last_name
                - email
                - password
              properties:
                username:
                  type: string
                  example: JohnDoe345
                first_name:
                  type: string
                  example: John
                last_name:
                  type: string
                  example: Doe
                email:
                  type: string
                  example: johndoe345@gmail.com
                password:
                  type: string
                  example: passwd234
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Kode OTP dikirim ke email kamu.
                  data:
                    type: object
                    properties:
                      user_id:
                        type: number
                        example: 1
                      email:
                        type: string
                        example: johndoe345@gmail.com
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Tolong isi semua formulir.
  # Verify token
  /auth/verify-otp:
    post:
      tags:
        - Authentication
      description: Verification OTP and activate account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - otp
              properties:
                email:
                  type: string
                  example: johndoe345@gmail.com
                otp:
                  type: string
                  example: 12345

      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Verifikasi Akun sukses.
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example:
                      refresh_token:
                        type: string
                        example:
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Tolong masukkan otp yang benar.
